In [204]:
import torch
from torch import nn
conv = nn.Conv1d
c = 5 # input chan
m = 1 #num filters
k = 3 #kernel size
b = 1; T = 7  #batch and samples 
x = torch.randn(b, c, T)
x.size()

torch.Size([1, 5, 7])

In [205]:
conv = nn.Conv1d(c, m, k, stride=2)
conv

Conv1d(5, 1, kernel_size=(3,), stride=(2,))

In [206]:
conv.weight.size()

torch.Size([1, 5, 3])

In [207]:
conv.weight

Parameter containing:
tensor([[[ 0.0427,  0.1647,  0.1430],
         [-0.2414,  0.1162,  0.1497],
         [-0.2274, -0.1563,  0.0197],
         [-0.1237, -0.1991,  0.0955],
         [-0.2346, -0.1136,  0.1031]]], requires_grad=True)

In [208]:
conv.bias.size()

torch.Size([1])

In [209]:
conv(x).size()

torch.Size([1, 1, 3])

In [210]:
conv(x)

tensor([[[-0.8442,  0.1802, -1.3545]]], grad_fn=<ConvolutionBackward0>)

In [211]:
convt = nn.ConvTranspose1d(c, m, k, stride=2)

In [212]:
convt(x).size()

torch.Size([1, 1, 15])

In [213]:
convt(x)

tensor([[[ 1.9907,  0.4517,  1.3597, -0.9754,  1.4188,  0.8585, -1.7298,
          -0.6182,  3.4652,  0.3960,  3.1162, -0.4183,  0.3630,  0.2758,
           0.1048]]], grad_fn=<ConvolutionBackward0>)